import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { ThemeProvider } from "@/components/ThemeProvider/ThemeProvider";
import { StickyBanner } from "@/components/ui/sticky-banner";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dr. Rajeev's Wellness Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StickyBanner className="bg-gradient-to-b from-ring to-primary" hideOnScroll={true}>
            <p className="mx-0 max-w-[90%] text-white drop-shadow-md">
              Announcing New Course Launch.{" "}
              <a href="#" className="transition duration-200 hover:underline">
                Read announcement
              </a>
            </p>
          </StickyBanner>
          <Header />
          {children}
          <Footer/ >
        </ThemeProvider>
      </body>
    </html>
  );
}
